repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [ '--safe' ]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
          # E501 let black handle all line length decisions
          # W503 black conflicts with "line break before operator" rule
          # E203 black conflicts with "whitespace before ':'" rule
          '--ignore=E501,W503,E203,C901,E231,E702' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: /tests/
        # --strict
        args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --implicit-reexport,
          --explicit-package-bases,
        ]
        additional_dependencies: [
          "types-attrs",
          "types-requests",
          "types-redis"
        ]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: '.*(test|alembic|scripts).*'
          #args: [
        # Don't require docstrings for tests
        #'--match=(?!test|alembic|scripts).*\.py',
        #]
  - repo: local
    hooks:
      - id: helm-chart-lint
        name: Helm chart lint
        language: docker_image
        entry: quay.io/helmpack/chart-testing:v3.7.1
        args:
          - bash
          - -c
          - >-
            export HELM_CONFIG_HOME=/tmp/helm &&
            export HELM_DATA_HOME=/tmp/helm &&
            export HELM_CACHE_HOME=/tmp/helm &&
            ct lint --config /src/.github/ct.yaml
        pass_filenames: false
        files: ^helm-chart/