services:
  app-elasticsearch:
    container_name: stac-fastapi-es
    image: stac-utils/stac-fastapi-es
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev.es
    environment:
      - STAC_FASTAPI_TITLE=stac-fastapi-elasticsearch
      - STAC_FASTAPI_DESCRIPTION=A STAC FastAPI with an Elasticsearch backend
      - STAC_FASTAPI_VERSION=6.0.0
      - STAC_FASTAPI_LANDING_PAGE_ID=stac-fastapi-elasticsearch
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USE_SSL=false
      - ES_VERIFY_CERTS=false
      - ES_TIMEOUT=30
      - BACKEND=elasticsearch
      - DATABASE_REFRESH=true
      - ENABLE_COLLECTIONS_SEARCH_ROUTE=true
      - ENABLE_CATALOGS_ROUTE=true
      - REDIS_ENABLE=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
      - ./esdata:/usr/share/elasticsearch/data
    depends_on:
      - elasticsearch
      - redis
    command:
      bash -c "./scripts/wait-for-it-es.sh es-container:9200 && python -m stac_fastapi.elasticsearch.app"

  app-opensearch:
    container_name: stac-fastapi-os
    image: stac-utils/stac-fastapi-os
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev.os
    environment:
      - STAC_FASTAPI_TITLE=stac-fastapi-opensearch
      - STAC_FASTAPI_DESCRIPTION=A STAC FastAPI with an Opensearch backend
      - STAC_FASTAPI_VERSION=6.0.0
      - STAC_FASTAPI_LANDING_PAGE_ID=stac-fastapi-opensearch
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - ES_HOST=opensearch
      - ES_PORT=9202
      - ES_USE_SSL=false
      - ES_VERIFY_CERTS=false
      - ES_TIMEOUT=30
      - BACKEND=opensearch
      - STAC_FASTAPI_RATE_LIMIT=200/minute
      - ENABLE_COLLECTIONS_SEARCH_ROUTE=true
      - ENABLE_CATALOGS_ROUTE=true
      - REDIS_ENABLE=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8082:8082"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
      - ./osdata:/usr/share/opensearch/data
    depends_on:
      - opensearch
      - redis
    command:
      bash -c "./scripts/wait-for-it-es.sh os-container:9202 && python -m stac_fastapi.opensearch.app"

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-8.19.5}
    hostname: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx1g
      action.destructive_requires_name: false
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"

  opensearch:
    container_name: os-container
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-2.19.3}
    hostname: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - action.destructive_requires_name=false
    volumes:
      - ./opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch/snapshots:/usr/share/opensearch/snapshots
    ports:
      - "9202:9202"

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server
volumes:
  redis_test_data:
